### ISSUE TITLE
Compilation halts at standard-to-thirties.xfscript

### ISSUE THREAD

**Issue by Trondtr** [giellalt/lang-mrj#1]
To repeat:
./configure (my version was:  ./configure --with-hfst --enable-reversed-intersect --enable-tokenisers)
make 

Error message:
make[2]: *** No rule to make target `standard-to-thirties.xfscript', needed by `standard-to-thirties.hfst'.  Stop.
The error is linked to recent cleanup for standard-to-eighties.

**Comment by Trondtr** [comment]
The situation for mrj is the following: Despite Alho Alhoniemis grammar, there actually are three orthographies:
- 1938: (parallel to the mhr from same period, see standard-to-thirties.xfscript)
- 1939-1994: Parallel to mrj from post-1939, but with front vowels noninitially written as back vowel (as Finnish "Jämsa")
- 1995-: Like the previous orthography, but now also with non-initial front vowels spelled out (as Finnish "Jämsä")

We thus need both the standard-to-thirties and standard-to-eighties.

At present the situation blocks the ongoing Korp update, so I would like to give it priority.

**Comment by snomos** [comment]
@rueter and I decided to name one orthography `1938` -  I believe it corresponds to the one for the period 1939-1994 above, but Jack can correct me on that. Presently that is the only orthography in addition to the modern standard that is properly handled. More orthographies can be added as needed, of course.
