### ISSUE TITLE
src/filters/rename-POS_before_Der-tags.regex does not give Ex/Pos effect

### ISSUE THREAD

**Issue by Trondtr** [giellalt/lang-mrj#3]
The script was added based upon the similar one in lang-mhr, and accompanied with reference in src/Makefile.am and src/filters/Makefile.am, likewise as in leng-mhr.

The result after ./autogen.sh and compilation is as follows:

```sh
echo "Материальный" |hfst-tokenise -cg tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
"<Материальный>"
	"материальный" A Der/N N Sg Nom <W:0.0>
	"материальный" A Pos <W:0.0>
```
where we would have wanted

	"материальный" Ex/A Der/N N Sg Nom <W:0.0>

**Comment by snomos** [comment]
Do all derivations have a tag `+Der` or `+DerN` (N=1..n) in front of the derivation analysis tag (`+Der/N` in this case)? If not, the filter does not have the context it needs to do the tag renaming.

**Comment by snomos** [comment]
> Do all derivations have a tag `+Der` or `+DerN` (N=1..n) in front of the derivation analysis tag (`+Der/N` in this case)? If not, the filter does not have the context it needs to do the tag renaming.

Answering myself:

```sh
grep '+Der/N' src/fst/lexicon.tmp.lexc 
 +Der/N !! Noun derivation
 +Der/N+N:           NMN_OLMA ; !! This should be neutral 2013-05-11
 +Der/N+N:%{back%}      NMN_OLMA ;
 +Der/N+N:%{front%}      NMN_AEZAE ;
 +Der/N+N:%{back%}      NMN_MARY ;
 +Der/N+N:%{front%}      NMN_TYERVYE ;
 +Der/N+N:%{back%}      NMN_KOL ; !!≈ * __@CODE@__ The +N tag is given here to curtail over generation from derived nouns
 +Der/N+N:%{front%}      NMN_MOER ; !!≈ * __@CODE@__ The +N tag is given here to curtail over generation from derived nouns
```

That is, none of the derivations have a preceding tag `+Der`, `+Der1` .. `+DerN`, and thus the filter can not work. As a minimum, add `+Der` in front of all `+Der/N`, and you should be good to go.

**Comment by Trondtr** [comment]
Yes, all tags +Der/... (there are four of them) do have a tag +Der preceding them:

uit-mac-443:lang-mrj ttr000$ grep 'Der/' src/fst/*/*|grep -v 'Der+Der'
uit-mac-443:lang-mrj ttr000$ grep 'Der/' src/fst/*/* |wc -l
      31

Examples:
src/fst/lexicon.tmp.lexc: +Der+Der/N+N:%{front%}      NMN_MOER ;
src/fst/lexicon.tmp.lexc:        +Der+Der/дЫмЫ+NegPrc:%>д%{ыӹ%}м%{ыӹØ%}                 NMN_TYERVYE ;

Trond Trosterud
Giellatekno, UiT Noregs arktiske universitet
trond.trosterud@uit.n
0047 776 44763

________________________________________
Lähettäjä: Sjur Moshagen <notifications@github.com>
Lähetetty: torstai 7. tammikuuta 2021 17.46
Vastaanottaja: giellalt/lang-mrj
Kopio: Trond Trosterud; Author
Aihe: Re: [giellalt/lang-mrj] src/filters/rename-POS_before_Der-tags.regex does not give Ex/Pos effect (#3)

Do all derivations have a tag +Der or +DerN (N=1..n) in front of the derivation analysis tag (+Der/N in this case)? If not, the filter does not have the context it needs to do the tag renaming.

Answering myself:

grep '+Der/N' src/fst/lexicon.tmp.lexc

 +Der/N !! Noun derivation

 +Der/N+N:           NMN_OLMA ; !! This should be neutral 2013-05-11

 +Der/N+N:%{back%}      NMN_OLMA ;

 +Der/N+N:%{front%}      NMN_AEZAE ;

 +Der/N+N:%{back%}      NMN_MARY ;

 +Der/N+N:%{front%}      NMN_TYERVYE ;

 +Der/N+N:%{back%}      NMN_KOL ; !!≈ * __@CODE@__ The +N tag is given here to curtail over generation from derived nouns

 +Der/N+N:%{front%}      NMN_MOER ; !!≈ * __@CODE@__ The +N tag is given here to curtail over generation from derived nouns

That is, none of the derivations have a preceding tag +Der, +Der1 .. +DerN, and thus the filter can not work. As a minimum, add +Der in front of all +Der/N, and you should be good to go.

**Comment by snomos** [comment]
Fixed:

```sh
echo Материальный | hfst-tokenise -g tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
"<Материальный>"
	"материальный" A Pos <W:0.0>
	"материальный" Ex/A Der Der/N N Sg Nom <W:0.0>
:\n
```
